# LABORATORIO CALIFICADO N° 01
## Fundamentos de Gestión de Datos

| | |
|:---|:---|
| **Curso** | Fundamentos de Gestión de Datos |
| **Semana** | 3 |
| **Tema** | Estructura de datos: filas, columnas y tipos de variables |
| **Herramienta** | Google Colab + Python |
| **Docente** | Pilar Rocío Sayán Mejía |
| **Semestre** | 2026-I |
| **Sección** | *(Escribe tu sección)* |
| **Fecha** | *(Escribe la fecha)* |

---

## Integrantes del grupo

| N.° | Apellidos y nombres | Rol |
|:---|:---|:---|
| 1 | ____________________________________________ | **Jefe de grupo** |
| 2 | ____________________________________________ | Integrante |
| 3 | ____________________________________________ | Integrante |
| 4 | ____________________________________________ | Integrante |

---

> **Indicaciones:** Laboratorio grupal. Ejecuta cada celda en orden y responde **todas** las preguntas. No borres celdas ni cambies el código dado.

---
## Competencia

Identifica la estructura de un conjunto de datos (filas, columnas y tipos de datos)
y clasifica sus variables como cuantitativas o cualitativas,
interpretando los resultados en un contexto real de análisis.

# Introducción — Conceptos clave

## ¿Qué es una variable?

Una variable es cada columna de un conjunto de datos.  
Representa una característica que se mide u observa en cada registro (fila).

---

# Clasificación de variables

| Tipo | Subtipo | Descripción | Ejemplo |
|:---|:---|:---|:---|
| Cuantitativa | Continua | Toma cualquier valor numérico en un rango | Peso: 65.3 kg, temperatura: 36.7 °C |
| Cuantitativa | Discreta | Solo valores enteros contables | Número de hijos: 0, 1, 2, 3 |
| Cualitativa | Nominal | Categorías sin orden entre sí | Color, país, género |
| Cualitativa | Ordinal | Categorías con orden lógico | Nivel: básico < medio < superior |

---

# Tipos de dato en pandas

| Tipo pandas | Significado | Tipo de variable probable |
|:---|:---|:---|
| `float64` | Número decimal | Cuantitativa continua |
| `int64` | Número entero | Cuantitativa discreta o cualitativa (si son códigos) |
| `object` | Texto | Cualitativa nominal |

> **Importante:** Un `int64` no siempre es cuantitativo.  
> Si los valores son códigos (0 = No, 1 = Sí), la variable es cualitativa nominal.

---

# Tabla de conceptos — completa ANTES de iniciar el laboratorio

> Esta tabla se evalúa. Escribe con tus propias palabras.

| Concepto | Definición con tus propias palabras |
|:---|:---|
| Variable cuantitativa continua | |
| Variable cuantitativa discreta | |
| Variable cualitativa nominal | |
| DataFrame | |
| float64 | |
| int64 | |
| object | |
| `.shape` | |
| `.dtypes` | |
| `.info()` | |

---

# VI. PROCEDIMIENTO

# CASO 1 — Dataset de automóviles (mtcars)

## Contexto

Eres analista de datos en la consultora **AutoData S.A.**  
Un cliente fabricante de vehículos te entrega el dataset `mtcars`, el cual contiene información técnica de distintos modelos de automóviles.

Antes de realizar cualquier modelo predictivo o análisis avanzado, tu primera tarea consiste en comprender la estructura del dataset y clasificar correctamente las variables.

---

# Paso 1 — Cargar el dataset desde URL

- `pd.read_csv(url)` carga un archivo CSV desde internet en un DataFrame.
- `index_col=0` usa la primera columna (nombre del modelo) como índice de filas.
- `df.head(5)` muestra los primeros 5 registros para una revisión rápida.

In [ ]:
import pandas as pd

# Cargar mtcars desde URL pública
url = 'https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/datasets/mtcars.csv'

df_autos = pd.read_csv(url, index_col=0)

print('Dataset cargado correctamente.')
print(df_autos.head(5))

Dataset cargado correctamente.
                    mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
rownames
Mazda RX4          21.0    6  160.0  110  3.90  2.620  16.46   0   1     4
Mazda RX4 Wag      21.0    6  160.0  110  3.90  2.875  17.02   0   1     4
Datsun 710         22.8    4  108.0   93  3.85  2.320  18.61   1   1     4
Hornet 4 Drive     21.4    6  258.0  110  3.08  3.215  19.44   1   0     3
Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3

                   carb
rownames
Mazda RX4             4
Mazda RX4 Wag         4
Datsun 710            1
Hornet 4 Drive        1
Hornet Sportabout     2


---

# La empresa necesita responder las siguientes preguntas

## Pregunta 1.1

¿Qué representa cada fila del dataset? ¿Y cada columna?

📝 **Tu respuesta:**  

---

## Pregunta 1.2

Como analista de AutoData S.A., ¿qué columna te parece más importante a primera vista para comparar eficiencia de combustible entre autos? ¿Por qué?

📝 **Tu respuesta:**

---
## PARTE 2 — Consultas SQL con SQLite: Farmacia

En esta parte crearemos una base de datos de una farmacia con tres tablas
relacionadas y practicaremos consultas SQL básicas.

---

> **Nota importante sobre la visualización de resultados**
>
> En esta parte usamos **SQL puro** para filtrar, calcular y ordenar datos.
> pandas **no** se usa para filtrar ni calcular: solo usamos
> `pd.read_sql_query()` al final de cada consulta para **mostrar**
> el resultado como tabla con encabezados claros.
> (Si usáramos `cursor.fetchall()`, el resultado sería una lista de tuplas
> sin nombres de columna, difícil de leer.)

### Preparación: crear la base de datos de la farmacia

Ejecuta esta celda **una sola vez** para crear la base de datos.
Puedes volver a ejecutarla si necesitas reiniciar — borra y recrea todo automáticamente.

#### Estructura de la base de datos

```
clientes (cliente_id PK, nombre, ciudad)
     |
     |--- ventas (venta_id PK, cliente_id FK, medicamento, categoria,
     |            ciudad, cantidad, monto, fecha)
     |
medicamentos (medicamento_id PK, nombre UNIQUE NOT NULL, categoria, precio)
```

- **PK** = Clave Primaria (PRIMARY KEY): identifica de forma única cada fila.
- **FK** = Clave Foránea (FOREIGN KEY): conecta una tabla con otra.
- **NOT NULL**: el campo no puede quedar vacío.
- **UNIQUE**: el valor no puede repetirse en esa columna.

# Paso 2 — Renombrar columnas al español

Los nombres originales son abreviaciones en inglés.  
Se renombran al español para facilitar la comunicación con el cliente.

---

# Diccionario de variables — mtcars

| Variable (español) | Variable original | Descripción detallada | Tipo de dato | Tipo de variable |
|:---|:---|:---|:---|:---|
| millas_por_galon | mpg | Consumo: millas recorridas por galón de combustible | | |
| cilindros | cyl | Número de cilindros del motor (4, 6 u 8) | | |
| desplazamiento | disp | Volumen total de los cilindros del motor (pulg³) | | |
| caballos_fuerza | hp | Potencia máxima del motor en HP | | |
| relacion_eje | drat | Relación de transmisión del eje trasero | | |
| peso | wt | Peso del vehículo en miles de libras | | |
| tiempo_cuarto_milla | qsec | Segundos en recorrer un cuarto de milla | | |
| tipo_motor | vs | Configuración: 0 = en V, 1 = en línea | | |
| transmisión | am | Transmisión: 0 = automática, 1 = manual | | |
| velocidades | gear | Número de marchas (3, 4 o 5) | | |
| carburadores | carb | Número de carburadores del motor | | |

---

In [ ]:

# Renombrar columnas al español
df_autos.columns = [
    'millas_por_galon',
    'cilindros',
    'desplazamiento',
    'caballos_fuerza',
    'relacion_eje',
    'peso',
    'tiempo_cuarto_milla',
    'tipo_motor',
    'transmision',
    'velocidades',
    'carburadores'
]
print('Columnas renombradas:')
print(df_autos.columns.tolist())

print()
print(df_autos.head(3))

Columnas renombradas:
['millas_por_galon', 'cilindros', 'desplazamiento', 'caballos_fuerza', 'relacion_eje', 'peso', 'tiempo_cuarto_milla', 'tipo_motor', 'transmision', 'velocidades', 'carburadores']

               millas_por_galon  cilindros  desplazamiento  caballos_fuerza  \
rownames
Mazda RX4                  21.0          6           160.0              110
Mazda RX4 Wag              21.0          6           160.0              110
Datsun 710                 22.8          4           108.0               93

               relacion_eje   peso  tiempo_cuarto_milla  tipo_motor  \
rownames
Mazda RX4              3.90  2.620                16.46           0
Mazda RX4 Wag          3.90  2.875                17.02           0
Datsun 710             3.85  2.320                18.61           1

               transmision  velocidades  carburadores
rownames
Mazda RX4                1            4             4
Mazda RX4 Wag            1            4             4
Datsun 710               1            4             1


## Pregunta 1.3

Consulta el diccionario.  
¿Qué diferencia hay entre `tipo_motor` y `cilindros` si ambos son `int64`?  
¿Por qué uno es cualitativo y el otro cuantitativo?

📝 **Tu respuesta:**  

---

## Pregunta 1.4

¿Por qué `transmision` tiene valores 0 y 1 pero se clasifica como cualitativa y no cuantitativa?

📝 **Tu respuesta:**  

---

# Paso 3 — Estructura del dataset

`.shape` devuelve `(filas, columnas)`.  
Es lo primero que reportas como analista al presentar un dataset nuevo.

In [ ]:

# Estructura del dataset
filas, columnas = df_autos.shape

print('Filas (registros): ', filas)
print('Columnas (variables): ', columnas)

Filas (registros):  32
Columnas (variables):  11

---

## Pregunta 1.5

El cliente de AutoData S.A. pregunta:

> ¿Cuántos modelos de autos y cuántas características por modelo tiene el dataset?

Respóndele como analista, sin tecnicismos.

📝 **Tu respuesta:**  

---

# Paso 4 — Tipos de datos

- `.dtypes` muestra el tipo de dato de cada columna.
- `.info()` da un resumen completo: tipo, valores no nulos y uso de memoria.

> Revisa esto siempre antes de analizar: un tipo incorrecto puede arruinar los cálculos.

In [ ]:

# Tipos de dato por columna
print('Tipos de dato:')
print(df_autos.dtypes)
# Información completa del dataset
df_autos.info()

Tipos de dato:
millas_por_galon       float64
cilindros                int64
desplazamiento         float64
caballos_fuerza          int64
relacion_eje           float64
peso                   float64
tiempo_cuarto_milla    float64
tipo_motor               int64
transmision              int64
velocidades              int64
carburadores             int64
dtype: object
<class 'pandas.core.frame.DataFrame'>
Index: 32 entries, Mazda RX4 to Volvo 142E
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   millas_por_galon     32 non-null     float64
 1   cilindros            32 non-null     int64
 2   desplazamiento       32 non-null     float64
 3   caballos_fuerza      32 non-null     int64
 4   relacion_eje         32 non-null     float64
 5   peso                 32 non-null     float64
 6   tiempo_cuarto_milla  32 non-null     float64
 7   tipo_motor           32 non-null     int64
 8   transmision          32 non-null     int64
 9   velocidades          32 non-null     int64
 10  carburadores         32 non-null     int64
dtypes: float64(5), int64(6)
memory usage: 3.0+ KB

---

## Pregunta 1.6

¿Cuántas variables son `float64` y cuántas son `int64`?  
¿Hay alguna `object`?  
¿Qué significa que no haya ninguna de tipo `object`?

📝 **Tu respuesta:**  

---

## Pregunta 1.7

¿Hay valores nulos en el dataset?  
¿Cómo lo confirmas con `.info()`?

📝 **Tu respuesta:**  

---

# Paso 5 — Identificar variables cuantitativas y cualitativas

`select_dtypes(include=[...])` filtra columnas por tipo de dato.  
Esto separa automáticamente las variables numéricas de las de texto.

```python
# Variables numéricas
vars_numericas = df_autos.select_dtypes(
    include=['float64', 'int64']
).columns.tolist()

print('Variables numéricas (float64 / int64):')
print(vars_numericas)

print()

# Variables de texto
vars_texto = df_autos.select_dtypes(
    include=['object']
).columns.tolist()

print('Variables de texto (object):')
print(vars_texto)
```

---

## Pregunta 1.8

`tipo_motor`, `transmision` y `velocidades` aparecen como `int64` pero son cualitativas según el diccionario.

¿Qué riesgo hay si las tratamos como números para calcular promedios?

📝 **Tu respuesta:**  

---

## Pregunta 1.9

Completa la tabla de clasificación usando el diccionario y los resultados obtenidos.

| Variable | Tipo pandas | Tipo de variable real | Justificación breve |
|:---|:---|:---|:---|
| millas_por_galon | float64 | | |
| cilindros | int64 | | |
| desplazamiento | float64 | | |
| caballos_fuerza | int64 | | |
| peso | float64 | | |
| tipo_motor | int64 | | |
| transmisión | int64 | | |
| velocidades | int64 | | |

---

# Paso 6 — Estadísticas básicas

`.describe()` calcula:

- conteo
- promedio
- desviación estándar
- mínimo
- cuartiles
- máximo

Es el resumen inicial que todo analista presenta al cliente.

In [ ]:

# Estadísticas descriptivas
print('Estadísticas descriptivas de mtcars:')
print(df_autos.describe())

Estadísticas descriptivas de mtcars:
       millas_por_galon  cilindros  desplazamiento  caballos_fuerza  \
count         32.000000  32.000000       32.000000        32.000000
mean          20.090625   6.187500      230.721875       146.687500
std            6.026948   1.785922      123.938694        68.562868
min           10.400000   4.000000       71.100000        52.000000
25%           15.425000   4.000000      120.825000        96.500000
50%           19.200000   6.000000      196.300000       123.000000
75%           22.800000   8.000000      326.000000       180.000000
max           33.900000   8.000000      472.000000       335.000000

       relacion_eje       peso  tiempo_cuarto_milla  tipo_motor  transmision  \
count     32.000000  32.000000            32.000000   32.000000    32.000000
mean       3.596563   3.217250            17.848750    0.437500     0.406250
std        0.534679   0.978457             1.786943    0.504016     0.498991
min        2.760000   1.513000            14.500000    0.000000     0.000000
25%        3.080000   2.581250            16.892500    0.000000     0.000000
50%        3.695000   3.325000            17.710000    0.000000     0.000000
75%        3.920000   3.610000            18.900000    1.000000     1.000000
max        4.930000   5.424000            22.900000    1.000000     1.000000

       velocidades  carburadores
count    32.000000       32.0000
mean      3.687500        2.8125
std       0.737804        1.6152
min       3.000000        1.0000
25%       3.000000        2.0000
50%       4.000000        2.0000
75%       4.000000        4.0000
max       5.000000        8.0000


---

## Pregunta 1.10

El cliente pregunta:

> “¿Cuál es la eficiencia de combustible promedio y cuál es la diferencia entre el auto más eficiente y el menos eficiente?”

Respóndele usando los datos del resultado.

📝 **Tu respuesta:**  

---

## Pregunta 1.11

Como analista, ¿qué conclusión le darías al cliente sobre la potencia (`caballos_fuerza`) de los autos del dataset?

Usa mínimo, máximo y promedio.

📝 **Tu respuesta:**

# PARTE 2 — Consultas SQL con SQLite: Farmacia

## Caso: Base de datos para el análisis de ventas de una farmacia

Eres analista de datos en una pequeña cadena de farmacias que desea organizar mejor la información de sus ventas. Hasta el momento, los registros se han manejado de forma manual, por lo que resulta difícil saber qué medicamentos se venden más, en qué ciudades se concentran las ventas y cuál es el monto promedio de compra.

Para resolver este problema, se te solicita crear una base de datos sencilla en **SQLite**. Esta base permitirá almacenar información de clientes, medicamentos y ventas realizadas. A partir de esta información, deberás ejecutar consultas SQL básicas que ayuden a responder preguntas comerciales importantes para la farmacia.

En esta parte del laboratorio trabajarás con **SQL puro**. Esto significa que todo el filtrado, cálculo y ordenamiento de los datos debe realizarse mediante instrucciones SQL como `SELECT`, `WHERE`, `AVG`, `MAX`, `MIN`, `COUNT` y `ORDER BY`.

`pandas` solo se usará al final de cada consulta con `pd.read_sql_query()` para mostrar los resultados en forma de tabla. No debes usar pandas para filtrar, calcular ni ordenar los datos.

---

## Estructura de la base de datos

La base de datos estará compuesta por tres tablas relacionadas:

```text
clientes     (cliente_id PK, nombre NOT NULL, ciudad NOT NULL)

medicamentos (medicamento_id PK, nombre NOT NULL UNIQUE, categoria NOT NULL, precio NOT NULL)

ventas       (venta_id PK, cliente_id FK -> clientes,
              medicamento, categoria, ciudad,
              cantidad NOT NULL, monto NOT NULL, fecha NOT NULL)
```

---

## Significado de las restricciones

| Abreviatura / Restricción | Significado |
|:---|:---|
| `PK` | Clave primaria. Identifica de manera única cada registro de una tabla. |
| `FK` | Clave foránea. Relaciona una tabla con otra. |
| `NOT NULL` | Indica que el campo no puede quedar vacío. |
| `UNIQUE` | Indica que los valores no se pueden repetir. |

---

## Celda de preparación — ejecutar una sola vez

Antes de realizar las consultas, primero debes crear la base de datos `farmacia.db`, definir sus tablas e insertar los registros iniciales.

# PARTE 2 — Consultas SQL con SQLite: Farmacia

Crearemos una base de datos SQLite de una farmacia con tres tablas relacionadas y practicaremos consultas SQL básicas.

---

## ⚠️ Regla importante: SQL puro en esta parte

Todo el **filtrado**, **cálculo** y **ordenamiento** se hace con SQL.

`pandas` solo se usa al final de cada consulta con `pd.read_sql_query()` para **mostrar el resultado** como tabla con encabezados claros.

> No usar pandas para filtrar, calcular ni ordenar.  


---

# Estructura de la base de datos

La base de datos tiene tres tablas relacionadas:

```text
clientes     (cliente_id PK, nombre NOT NULL, ciudad NOT NULL)

medicamentos (medicamento_id PK, nombre NOT NULL UNIQUE, categoria NOT NULL, precio NOT NULL)

ventas       (venta_id PK, cliente_id FK -> clientes,
              medicamento, categoria, ciudad,
              cantidad NOT NULL, monto NOT NULL, fecha NOT NULL)
```

---

## Significado de las restricciones

| Abreviatura / Restricción | Significado |
|:---|:---|
| `PK` | Clave Primaria |
| `FK` | Clave Foránea |
| `NOT NULL` | Campo obligatorio |
| `UNIQUE` | No permite valores repetidos |

---

# Celda de preparación

In [ ]:

import sqlite3
import pandas as pd
import os

DB_NAME = "farmacia.db"

# Eliminar la base anterior si ya existe
if os.path.exists(DB_NAME):
    os.remove(DB_NAME)

# Crear conexión
conexion = sqlite3.connect(DB_NAME)

# Crear cursor
cursor = conexion.cursor()

print("Base de datos creada correctamente.")

# ═══════════════════════════════════════════════════════════════════════════
# CREAR TABLAS
# ═══════════════════════════════════════════════════════════════════════════

# Tabla 1: clientes
#   cliente_id → PRIMARY KEY (identificador único de cada cliente)
#   nombre, ciudad → NOT NULL (campos obligatorios)
cursor.execute("""
CREATE TABLE clientes (
    cliente_id  INTEGER  PRIMARY KEY,
    nombre      TEXT     NOT NULL,
    ciudad      TEXT     NOT NULL
);
""")

# Tabla 2: medicamentos
#   medicamento_id → PRIMARY KEY
#   nombre → NOT NULL y UNIQUE (no puede haber dos medicamentos con el mismo nombre)
#   precio → NOT NULL
cursor.execute("""
CREATE TABLE medicamentos (
    medicamento_id  INTEGER  PRIMARY KEY,
    nombre          TEXT     NOT NULL UNIQUE,
    categoria       TEXT     NOT NULL,
    precio          REAL     NOT NULL
);
""")

# Tabla 3: ventas
#   venta_id → PRIMARY KEY
#   cliente_id → FOREIGN KEY que apunta a clientes.cliente_id
#   cantidad y monto → NOT NULL
#   Se almacenan medicamento y categoria directamente para consultas simples sin JOIN
cursor.execute("""
CREATE TABLE ventas (
    venta_id    INTEGER  PRIMARY KEY,
    cliente_id  INTEGER  NOT NULL,
    medicamento TEXT     NOT NULL,
    categoria   TEXT     NOT NULL,
    ciudad      TEXT     NOT NULL,
    cantidad    INTEGER  NOT NULL,
    monto       REAL     NOT NULL,
    fecha       TEXT     NOT NULL,
    FOREIGN KEY (cliente_id) REFERENCES clientes(cliente_id)
);
""")

# ═══════════════════════════════════════════════════════════════════════════
# INSERTAR DATOS
# ═══════════════════════════════════════════════════════════════════════════

# 6 clientes
cursor.executemany("INSERT INTO clientes VALUES (?, ?, ?);", [
    (1, 'Ana Torres',    'Lima'),
    (2, 'Luis Quispe',   'Arequipa'),
    (3, 'María Ramos',   'Lima'),
    (4, 'Carlos Vega',   'Cusco'),
    (5, 'Sofía López',   'Trujillo'),
    (6, 'Diego Mendoza', 'Lima'),
])

# 6 medicamentos
cursor.executemany("INSERT INTO medicamentos VALUES (?, ?, ?, ?);", [
    (1, 'Amoxicilina',    'Antibiótico',       25.50),
    (2, 'Paracetamol',    'Analgésico',          8.00),
    (3, 'Ibuprofeno',     'Antiinflamatorio',   15.00),
    (4, 'Vitamina C',     'Vitamina',           12.00),
    (5, 'Omeprazol',      'Antiácido',          18.50),
    (6, 'Loratadina',     'Antialérgico',       22.00),
])

# 18 ventas
cursor.executemany("INSERT INTO ventas VALUES (?, ?, ?, ?, ?, ?, ?, ?);", [
    ( 1, 1, 'Paracetamol',   'Analgésico',       'Lima',      5,  40.00, '2026-03-01'),
    ( 2, 2, 'Amoxicilina',   'Antibiótico',      'Arequipa',  2,  51.00, '2026-03-01'),
    ( 3, 3, 'Ibuprofeno',    'Antiinflamatorio', 'Lima',      3,  45.00, '2026-03-02'),
    ( 4, 4, 'Vitamina C',    'Vitamina',         'Cusco',     4,  48.00, '2026-03-02'),
    ( 5, 5, 'Loratadina',    'Antialérgico',     'Trujillo',  2,  44.00, '2026-03-03'),
    ( 6, 6, 'Omeprazol',     'Antiácido',        'Lima',      3,  55.50, '2026-03-03'),
    ( 7, 1, 'Amoxicilina',   'Antibiótico',      'Lima',      1,  25.50, '2026-03-04'),
    ( 8, 2, 'Vitamina C',    'Vitamina',         'Arequipa',  6,  72.00, '2026-03-04'),
    ( 9, 3, 'Paracetamol',   'Analgésico',       'Lima',     10,  80.00, '2026-03-05'),
    (10, 4, 'Loratadina',    'Antialérgico',     'Cusco',     3,  66.00, '2026-03-05'),
    (11, 5, 'Ibuprofeno',    'Antiinflamatorio', 'Trujillo',  2,  30.00, '2026-03-06'),
    (12, 6, 'Omeprazol',     'Antiácido',        'Lima',      4,  74.00, '2026-03-06'),
    (13, 1, 'Loratadina',    'Antialérgico',     'Lima',      5, 110.00, '2026-03-07'),
    (14, 2, 'Paracetamol',   'Analgésico',       'Arequipa',  8,  64.00, '2026-03-07'),
    (15, 3, 'Amoxicilina',   'Antibiótico',      'Lima',      3,  76.50, '2026-03-08'),
    (16, 4, 'Vitamina C',    'Vitamina',         'Cusco',     5,  60.00, '2026-03-08'),
    (17, 5, 'Ibuprofeno',    'Antiinflamatorio', 'Trujillo',  4,  60.00, '2026-03-09'),
    (18, 6, 'Paracetamol',   'Analgésico',       'Lima',     12,  96.00, '2026-03-09'),
])

conexion.commit()

# ── Función de visualización ──────────────────────────────────────────────────
# Solo se usa para MOSTRAR resultados de consultas SQL.
# NO reemplaza SQL para filtrar ni calcular.
def mostrar(consulta_sql):
    return pd.read_sql_query(consulta_sql, conexion)

print("Base de datos 'farmacia.db' creada correctamente.")
print("Tablas: clientes (6 filas) | medicamentos (6 filas) | ventas (18 filas)")

Base de datos creada correctamente.
Base de datos 'farmacia.db' creada correctamente.
Tablas: clientes (6 filas) | medicamentos (6 filas) | ventas (18 filas)

---
### Consulta 1 — Ver todos los registros de ventas

`SELECT *` trae todas las columnas. `FROM ventas` indica la tabla.

In [ ]:
consulta = "SELECT * FROM ventas;"
mostrar(consulta)

,venta_id,cliente_id,medicamento,categoria,ciudad,cantidad,monto,fecha
0,1,1,Paracetamol,Analgésico,Lima,5,40.0,2026-03-01
1,2,2,Amoxicilina,Antibiótico,Arequipa,2,51.0,2026-03-01
2,3,3,Ibuprofeno,Antiinflamatorio,Lima,3,45.0,2026-03-02
3,4,4,Vitamina C,Vitamina,Cusco,4,48.0,2026-03-02
4,5,5,Loratadina,Antialérgico,Trujillo,2,44.0,2026-03-03
5,6,6,Omeprazol,Antiácido,Lima,3,55.5,2026-03-03
6,7,1,Amoxicilina,Antibiótico,Lima,1,25.5,2026-03-04
7,8,2,Vitamina C,Vitamina,Arequipa,6,72.0,2026-03-04
8,9,3,Paracetamol,Analgésico,Lima,10,80.0,2026-03-05
9,10,4,Loratadina,Antialérgico,Cusco,3,66.0,2026-03-05
10,11,5,Ibuprofeno,Antiinflamatorio,Trujillo,2,30.0,2026-03-06
11,12,6,Omeprazol,Antiácido,Lima,4,74.0,2026-03-06
12,13,1,Loratadina,Antialérgico,Lima,5,110.0,2026-03-07
13,14,2,Paracetamol,Analgésico,Arequipa,8,64.0,2026-03-07
14,15,3,Amoxicilina,Antibiótico,Lima,3,76.5,2026-03-08
15,16,4,Vitamina C,Vitamina,Cusco,5,60.0,2026-03-08
16,17,5,Ibuprofeno,Antiinflamatorio,Trujillo,4,60.0,2026-03-09
17,18,6,Paracetamol,Analgésico,Lima,12,96.0,2026-03-09

**Pregunta SQL 1** ¿Cuántas filas devuelve esta consulta? ¿Qué columnas contiene la tabla?

📝 **Tu respuesta:** *Escribe aquí...*

---
### Consulta 2 — Seleccionar columnas específicas

En lugar de `SELECT *`, podemos pedir solo las columnas que nos interesan.

In [ ]:
consulta = """
SELECT cliente_id, medicamento, ciudad, monto
FROM ventas;
"""
mostrar(consulta)

    cliente_id  medicamento    ciudad  monto
0            1  Paracetamol      Lima   40.0
1            2  Amoxicilina  Arequipa   51.0
2            3   Ibuprofeno      Lima   45.0
3            4   Vitamina C     Cusco   48.0
4            5   Loratadina  Trujillo   44.0
5            6    Omeprazol      Lima   55.5
6            1  Amoxicilina      Lima   25.5
7            2   Vitamina C  Arequipa   72.0
8            3  Paracetamol      Lima   80.0
9            4   Loratadina     Cusco   66.0
10           5   Ibuprofeno  Trujillo   30.0
11           6    Omeprazol      Lima   74.0
12           1   Loratadina      Lima  110.0
13           2  Paracetamol  Arequipa   64.0
14           3  Amoxicilina      Lima   76.5
15           4   Vitamina C     Cusco   60.0
16           5   Ibuprofeno  Trujillo   60.0
17           6  Paracetamol      Lima   96.0

**Pregunta SQL 2** ¿Qué columnas aparecen ahora? ¿Por qué es útil elegir solo algunas columnas?

📝 **Tu respuesta:** *Escribe aquí...*

---
### Consulta 3 — Filtrar ventas de Lima

`WHERE ciudad = 'Lima'` filtra solo las filas donde la ciudad es Lima.

In [ ]:
consulta = """
SELECT *
FROM ventas
WHERE ciudad = 'Lima';
"""
mostrar(consulta)

,venta_id,cliente_id,medicamento,categoria,ciudad,cantidad,monto,fecha
0,1,1,Paracetamol,Analgésico,Lima,5,40.0,2026-03-01
1,3,3,Ibuprofeno,Antiinflamatorio,Lima,3,45.0,2026-03-02
2,6,6,Omeprazol,Antiácido,Lima,3,55.5,2026-03-03
3,7,1,Amoxicilina,Antibiótico,Lima,1,25.5,2026-03-04
4,9,3,Paracetamol,Analgésico,Lima,10,80.0,2026-03-05
5,12,6,Omeprazol,Antiácido,Lima,4,74.0,2026-03-06
6,13,1,Loratadina,Antialérgico,Lima,5,110.0,2026-03-07
7,15,3,Amoxicilina,Antibiótico,Lima,3,76.5,2026-03-08
8,18,6,Paracetamol,Analgésico,Lima,12,96.0,2026-03-09

**Pregunta SQL 3** ¿Cuántas ventas se realizaron en Lima? ¿Qué medicamentos se vendieron allí?

📝 **Tu respuesta:** *Escribe aquí...*

---
### Consulta 4 — Filtrar ventas de Arequipa o Cusco

`OR` permite incluir filas que cumplan **al menos una** de las condiciones.

In [ ]:
consulta = """
SELECT *
FROM ventas
WHERE ciudad = 'Arequipa'
OR ciudad = 'Cusco';
"""
mostrar(consulta)

,venta_id,cliente_id,medicamento,categoria,ciudad,cantidad,monto,fecha
0,2,2,Amoxicilina,Antibiótico,Arequipa,2,51.0,2026-03-01
1,4,4,Vitamina C,Vitamina,Cusco,4,48.0,2026-03-02
2,8,2,Vitamina C,Vitamina,Arequipa,6,72.0,2026-03-04
3,10,4,Loratadina,Antialérgico,Cusco,3,66.0,2026-03-05
4,14,2,Paracetamol,Analgésico,Arequipa,8,64.0,2026-03-07
5,16,4,Vitamina C,Vitamina,Cusco,5,60.0,2026-03-08

**Pregunta SQL 4** ¿Cuántas ventas hay entre Arequipa y Cusco en total?

📝 **Tu respuesta:** *Escribe aquí...*

---
### Consulta 5 — Filtrar por categoría

Filtramos solo los medicamentos de categoría `'Antibiótico'`.

In [ ]:
consulta = """
SELECT *
FROM ventas
WHERE categoria = 'Antibiótico';
"""
mostrar(consulta)

,venta_id,cliente_id,medicamento,categoria,ciudad,cantidad,monto,fecha
0,2,2,Amoxicilina,Antibiótico,Arequipa,2,51.0,2026-03-01
1,7,1,Amoxicilina,Antibiótico,Lima,1,25.5,2026-03-04
2,15,3,Amoxicilina,Antibiótico,Lima,3,76.5,2026-03-08

**Pregunta SQL 5** ¿Cuántas ventas de antibióticos hay? ¿En qué ciudades se vendieron?

📝 **Tu respuesta:** *Escribe aquí...*

---
### Consulta 6 — Promedio de ventas con AVG

`AVG(monto)` calcula el promedio de todos los valores de la columna `monto`.
`AS promedio_monto` le asigna un nombre al resultado.

In [ ]:
consulta = """
SELECT ROUND(AVG(monto), 2) AS promedio_monto
FROM ventas;
"""
mostrar(consulta)

   promedio_monto
0           60.97

**Pregunta SQL 6** ¿Cuál es el monto promedio de las ventas de la farmacia?

📝 **Tu respuesta:** *Escribe aquí...*

---
### Consulta 7 — Venta máxima con MAX

`MAX(monto)` devuelve el valor más alto de la columna `monto`.

In [ ]:
consulta = """
SELECT MAX(monto) AS monto_maximo
FROM ventas;
"""
mostrar(consulta)

   monto_maximo
0         110.0

**Pregunta SQL 7** ¿Cuál es la venta más alta registrada?

📝 **Tu respuesta:** *Escribe aquí...*

---
### Consulta 8 — Venta mínima con MIN

`MIN(monto)` devuelve el valor más bajo de la columna `monto`.

In [ ]:
consulta = """
SELECT MIN(monto) AS monto_minimo
FROM ventas;
"""
mostrar(consulta)

   monto_minimo
0          25.5

**Pregunta SQL 8** ¿Cuál es la venta más baja registrada?

📝 **Tu respuesta:** *Escribe aquí...*

---
### Consulta 9 — Contar registros con COUNT

`COUNT(*)` cuenta el número total de filas que devuelve la consulta.

In [ ]:
consulta = """
SELECT COUNT(*) AS total_registros
FROM ventas;
"""
mostrar(consulta)

   total_registros
0               18

**Pregunta SQL 9** ¿Cuántas ventas tiene registradas la farmacia en total?

📝 **Tu respuesta:** *Escribe aquí...*

---
### Consulta 10 — Ordenar de mayor a menor con ORDER BY

`ORDER BY monto DESC` ordena los resultados de mayor a menor.
Permite ver rápidamente las ventas más importantes.

In [ ]:
consulta = """
SELECT medicamento, ciudad, cantidad, monto
FROM ventas
ORDER BY monto DESC;
"""
mostrar(consulta)

    medicamento    ciudad  cantidad  monto
0    Loratadina      Lima         5  110.0
1   Paracetamol      Lima        12   96.0
2   Paracetamol      Lima        10   80.0
3   Amoxicilina      Lima         3   76.5
4     Omeprazol      Lima         4   74.0
5    Vitamina C  Arequipa         6   72.0
6    Loratadina     Cusco         3   66.0
7   Paracetamol  Arequipa         8   64.0
8    Vitamina C     Cusco         5   60.0
9    Ibuprofeno  Trujillo         4   60.0
10    Omeprazol      Lima         3   55.5
11  Amoxicilina  Arequipa         2   51.0
12   Vitamina C     Cusco         4   48.0
13   Ibuprofeno      Lima         3   45.0
14   Loratadina  Trujillo         2   44.0
15  Paracetamol      Lima         5   40.0
16   Ibuprofeno  Trujillo         2   30.0
17  Amoxicilina      Lima         1   25.5

**Pregunta SQL 10** ¿Qué venta aparece en primer lugar? ¿En qué ciudad ocurrió?

📝 **Tu respuesta:** *Escribe aquí...*

---
## PARTE 3 — Interpretación de resultados

Responde las siguientes preguntas basándote en los resultados de las Partes 1 y 2.
Escribe tu respuesta en cada celda de texto.

**Pregunta 3.1** ¿Qué ciudad presenta más ventas según las consultas SQL? ¿Qué estrategia comercial sugeriría esto para la farmacia?

📝 **Tu respuesta:** *Escribe aquí...*

**Pregunta 3.2** ¿Qué categoría de medicamento parece tener mayor monto de ventas? ¿Qué conclusión puedes sacar sobre los hábitos de compra de los clientes?

📝 **Tu respuesta:** *Escribe aquí...*

**Pregunta 3.3** ¿Qué información útil te dan el promedio, el máximo y el mínimo de ventas juntos? ¿Por qué no bastaría con solo uno de los tres?

📝 **Tu respuesta:** *Escribe aquí...*

**Pregunta 3.4** ¿Por qué SQL permite consultar datos directamente sin necesidad de modificar el DataFrame de pandas?

📝 **Tu respuesta:** *Escribe aquí...*

**Pregunta 3.5** ¿Cuál es la principal diferencia entre explorar datos con pandas (`df.head()`, `df.dtypes`) y consultar datos con SQL (`SELECT`, `WHERE`)?

📝 **Tu respuesta:** *Escribe aquí...*

---
## Conclusiones

Escribe tres conclusiones sobre lo que aprendiste en este laboratorio.

**1.** *Escribe tu primera conclusión aquí...*

**2.** *Escribe tu segunda conclusión aquí...*

**3.** *Escribe tu tercera conclusión aquí...*

In [ ]:
# Cerrar la conexión al terminar
try:
    cursor.close()
    conexion.close()
    print("Conexión cerrada correctamente.")
except Exception as e:
    print("Error al cerrar:", e)

print("Laboratorio completado.")

Conexión cerrada correctamente.
Laboratorio completado.

---
*2026-I — Fundamentos de Gestión de Datos — TECSUP — Docente: Pilar Rocío Sayán Mejía*